name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: alexchenqr/solidity-smart-contract:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npx hardhat --version
      - name: Run tests
        env:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          FORK_TEST_ADDR: ${{ secrets.FORK_TEST_ADDR }}
        run: npx hardhat clean && npx hardhat compile && npx hardhat test